server:
  port: 8761

eureka:
  client:
    register-with-eureka: false   #是否将自己注册到Eureka Server上，默认为true
    fetch-registry: false         #是否从Eureka Server上获取注册信息，默认为true
  server:
    enable-self-preservation: false

